gadgetgrove:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres-db
      user: postgres
      password: postgres
      port: 5432
      dbname: events
      schema: dbt_default # acts as a fallback, not used
      threads: 2
