services:
  webapp:
    build:
      context: ./webapp
    image: gadgetgrove-webapp:latest
    ports:
      - "8000:8000"
    volumes:
      - ./webapp:/app
      - logs:/var/log/webapp
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - postgres-db

  celery-worker:
    image: gadgetgrove-webapp:latest
    command: celery -A celery_app.celery_app worker --loglevel=info
    volumes:
      - logs:/var/log/celery
    env_file:
      - .env
    depends_on:
      - rabbitmq

  traffic-gen:
    image: gadgetgrove-webapp:latest
    command: python traffic_gen.py
    volumes:
      - ./webapp:/app
      - logs:/var/log/traffic-gen
    env_file:
      - .env
    depends_on:
      - webapp

  raw-consumer:
    image: gadgetgrove-webapp:latest
    command: python consumer.py
    volumes:
      - ./webapp:/app
      - data-landing:/data/raw
      - logs:/var/log/consumer
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - logs:/var/log/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 10s
      retries: 5

  postgres-db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - logs:/var/log/postgres
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  spark-master:
    image: bitnami/spark:3.5
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ./spark/jobs:/opt/spark/jobs
      - data-landing:/data
      - logs:/var/log/spark-master
    env_file:
      - .env

  spark-worker:
    image: bitnami/spark:3.5
    depends_on:
      - spark-master
    volumes:
      - data-landing:/data
      - logs:/var/log/spark-worker
    env_file:
      - .env

  prefect-server:
    image: prefecthq/prefect:3-latest
    command: prefect server start
    ports:
      - "4200:4200"
    volumes:
      - ./prefect:/app
      - logs:/var/log/prefect-server
    env_file:
      - .env
    depends_on:
      - postgres-db

  prefect-agent:
    image: prefecthq/prefect:3-latest
    command: prefect worker start --pool ${WORK_POOL}
    env_file:
      - .env
    depends_on:
      - prefect-server
    volumes:
      - ./prefect:/app
      - data-landing:/data
      - ./spark/jobs:/opt/spark/jobs
      - ./dbt:/opt/dbt
      - /var/run/docker.sock:/var/run/docker.sock
      - logs:/var/log/prefect-agent

  dbt:
    build:
      context: ./dbt
    image: dbt-postgres-arm64:latest
    working_dir: /usr/app
    volumes:
      - ./dbt:/usr/app
      - logs:/var/log/dbt
    depends_on:
      - postgres-db
    env_file:
      - .env

  init:
    image: gadgetgrove-webapp:latest
    command: init/run.sh
    user: root
    depends_on:
      postgres-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      prefect-server:
        condition: service_started
    volumes:
      - ./webapp:/app
      - ./prefect:/app/prefect
      - ./data:/app/data
      - logs:/var/log/init
    env_file:
      - .env

volumes:
  data-landing:
  postgres-data:
  rabbitmq-data:
  logs:
